"""Extracted from utils.py – generated by split_utils.py."""

def show_info_message(parent, title, message):
    """Show an information message with enhanced styling."""
    messagebox.showinfo(title, message)

def show_error_message(parent, title, message):
    """Show an error message with enhanced styling."""
    messagebox.showerror(title, message)

def show_warning_message(parent, title, message):
    """Show a warning message with enhanced styling."""
    messagebox.showwarning(title, message)

def show_confirmation_dialog(parent, title, message):
    """Show a confirmation dialog and return True if confirmed."""
    return messagebox.askyesno(title, message)
