"""Extracted from utils.py – generated by split_utils.py."""

def save_app_settings(settings, filename="app_settings.json"):
    """Save application settings to a JSON file."""
    try:
        with open(filename, 'w') as f:
            json.dump(settings, f, indent=2)
        return True
    except Exception as e:
        print(f"Error saving settings: {e}")
        return False

def load_app_settings(filename="app_settings.json"):
    """Load application settings from a JSON file."""
    if not os.path.exists(filename):
        return {}
    
    try:
        with open(filename, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading settings: {e}")
        return {}

def create_backup_file(filepath, suffix="_backup"):
    """Create a backup of a file with timestamp."""
    if not os.path.exists(filepath):
        return None
    
    # Get the file name and extension
    file_dir, file_name = os.path.split(filepath)
    name, ext = os.path.splitext(file_name)
    
    # Create a timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Create the backup file name
    backup_name = f"{name}{suffix}_{timestamp}{ext}"
    backup_path = os.path.join(file_dir, backup_name)
    
    # Copy the file
    try:
        import shutil
        shutil.copy2(filepath, backup_path)
        return backup_path
    except Exception as e:
        print(f"Error creating backup: {e}")
        return None
