# --- global spacing constants (were in the old utils.py)
PAD_X      = 8      # horizontal padding
PAD_Y      = 5      # vertical padding
FIELD_PAD  = 3      # label-entry gap

# --- feature flag: does the enhanced UI toolkit import?
try:
    from gui.ui.custom_widgets import FormulaEntry, TooltipButton, ProgressDialog
    USE_ENHANCED_UI = True
except ImportError:
    USE_ENHANCED_UI = False

"""Extracted from utils.py – generated by split_utils.py."""

# Color palette for a consistent look
PRIMARY_COLOR = "#1976D2"  # Material blue
SECONDARY_COLOR = "#42A5F5"  # Lighter blue
ACCENT_COLOR = "#FF9800"  # Orange accent
BG_COLOR = "#F5F5F5"  # Light grey background
TEXT_COLOR = "#212121"  # Dark text
PREVIEW_COLOR = "#607D8B"  # Blue grey for preview text
HEADER_COLOR = "#0D47A1"  # Dark blue for headers
SUCCESS_COLOR = "#4CAF50"  # Green for success indicators
