"""Extracted from utils.py – generated by split_utils.py."""

def create_status_bar(root, initial_message="Ready"):
    """Create a status bar at the bottom of the root window."""
    status_frame = ttk.Frame(root)
    status_frame.pack(side="bottom", fill="x", padx=5, pady=2)
    
    # Create a variable to hold the status text
    status_var = tk.StringVar(value=initial_message)
    
    # Create the status label
    status_label = ttk.Label(
        status_frame,
        textvariable=status_var,
        anchor="w",
        font=("Segoe UI", 9)
    )
    status_label.pack(side="left")
    
    # Return both the frame and the variable so they can be accessed later
    return status_frame, status_var

def flash_success_message(status_var, message, duration=3000):
    """Flash a success message in the status bar temporarily."""
    # Save the original message
    original_message = status_var.get()
    
    # Set the success message
    status_var.set(f"✓ {message}")
    
    # Schedule restoring the original message
    root = status_var.master.winfo_toplevel()
    root.after(duration, lambda: status_var.set(original_message))

def flash_error_message(status_var, message, duration=3000):
    """Flash an error message in the status bar temporarily."""
    # Save the original message
    original_message = status_var.get()
    
    # Set the error message
    status_var.set(f"❌ {message}")
    
    # Schedule restoring the original message
    root = status_var.master.winfo_toplevel()
    root.after(duration, lambda: status_var.set(original_message))
