import tkinter as tk          # ← add this
from tkinter import ttk       # ← and this

"""Extracted from utils.py – generated by split_utils.py."""
# …rest of the file unchanged …

"""Extracted from utils.py – generated by split_utils.py."""

def create_tooltip(widget, text):
    """Create a tooltip for a widget."""
    tooltip = None
    
    def enter(event):
        nonlocal tooltip
        x, y, _, _ = widget.bbox("insert")
        x += widget.winfo_rootx() + 25
        y += widget.winfo_rooty() + 25
        
        # Create a toplevel window
        tooltip = tk.Toplevel(widget)
        tooltip.wm_overrideredirect(True)
        tooltip.wm_geometry(f"+{x}+{y}")
        
        # Create the label
        label = ttk.Label(
            tooltip,
            text=text,
            justify=tk.LEFT,
            background="#FFFFD0",
            relief="solid",
            borderwidth=1,
            font=("Segoe UI", 9),
            padding=(5, 2)
        )
        label.pack()
    
    def leave(event):
        nonlocal tooltip
        if tooltip:
            tooltip.destroy()
            tooltip = None
    
    # Bind events to the widget
    widget.bind("<Enter>", enter)
    widget.bind("<Leave>", leave)

def create_help_button(parent, help_text):
    """Create a help button that shows a tooltip with provided text."""
    button = ttk.Button(
        parent,
        text="?",
        width=2,
        command=lambda: show_info_message(parent, "Help", help_text)
    )
    
    # Add a tooltip to the button
    create_tooltip(button, "Click for help")
    
    return button
